(ns functional-vaadin.config-table
  (:use [functional-vaadin.config-funcs])
  (:import (com.vaadin.ui
            Component AbstractComponent Label Embedded Link MenuBar CustomComponent Upload Button Calendar GridLayout
            TabSheet VerticalSplitPanel HorizontalSplitPanel Slider TextField TextArea PasswordField CheckBox
            RichTextArea InlineDateField PopupDateField Table ComboBox TwinColSelect NativeSelect
            ListSelect OptionGroup Tree TreeTable Panel VerticalLayout HorizontalLayout FormLayout)))

(def config-table
  {
    [:setAlternateText 1] (fn [obj arg0] (.setAlternateText obj arg0))
    [:setAnimationsEnabled 1] (fn [obj arg0] (.setAnimationsEnabled obj arg0))
    [:setArchive 1] (fn [obj arg0] (.setArchive obj arg0))
    [:setAssistiveText 1] (fn [obj arg0] (.setAssistiveText obj arg0))
    [:setAutoOpen 1] (fn [obj arg0] (.setAutoOpen obj arg0))
    [:setBuffered 1] (fn [obj arg0] (.setBuffered obj arg0))
    [:setButtonCaption 1] (fn [obj arg0] (.setButtonCaption obj arg0))
    [:setCacheRate 1] (fn [obj arg0] (.setCacheRate obj arg0))
    [:setCaption 1] (fn [obj arg0] (.setCaption obj arg0))
    [:setCaptionAsHtml 1] (fn [obj arg0] (.setCaptionAsHtml obj arg0))
    [:setCellStyleGenerator 1] (fn [obj arg0] (.setCellStyleGenerator obj arg0))
    [:setChildMeasurementHint 1] (fn [obj arg0] (.setChildMeasurementHint obj arg0))
    [:setChildrenAllowed 2] (fn [obj arg0 arg1] (.setChildrenAllowed obj arg0 arg1))
    [:setClassId 1] (fn [obj arg0] (.setClassId obj arg0))
    [:setClickShortcut 2] (fn [obj arg0 arg1] (.setClickShortcut obj arg0 arg1))
    [:setCloseHandler 1] (fn [obj arg0] (.setCloseHandler obj arg0))
    [:setCodebase 1] (fn [obj arg0] (.setCodebase obj arg0))
    [:setCodetype 1] (fn [obj arg0] (.setCodetype obj arg0))
    [:setCollapseMenuContent 1] (fn [obj arg0] (.setCollapseMenuContent obj arg0))
    [:setCollapsed 2] (fn [obj arg0 arg1] (.setCollapsed obj arg0 arg1))
    [:setColumnAlignment 2] (fn [obj arg0 arg1] (.setColumnAlignment obj arg0 arg1))
    [:setColumnAlignments 1] (fn [obj arg0] (.setColumnAlignments obj arg0))
    [:setColumnCollapsed 2] (fn [obj arg0 arg1] (.setColumnCollapsed obj arg0 arg1))
    [:setColumnCollapsible 2] (fn [obj arg0 arg1] (.setColumnCollapsible obj arg0 arg1))
    [:setColumnCollapsingAllowed 1] (fn [obj arg0] (.setColumnCollapsingAllowed obj arg0))
    [:setColumnExpandRatio 2] (fn [obj arg0 arg1] (.setColumnExpandRatio obj arg0 arg1))
    [:setColumnFooter 2] (fn [obj arg0 arg1] (.setColumnFooter obj arg0 arg1))
    [:setColumnHeader 2] (fn [obj arg0 arg1] (.setColumnHeader obj arg0 arg1))
    [:setColumnHeaderMode 1] (fn [obj arg0] (.setColumnHeaderMode obj arg0))
    [:setColumnHeaders 1] (fn [obj arg0] (.setColumnHeaders obj arg0))
    [:setColumnIcon 2] (fn [obj arg0 arg1] (.setColumnIcon obj arg0 arg1))
    [:setColumnIcons 1] (fn [obj arg0] (.setColumnIcons obj arg0))
    [:setColumnReorderingAllowed 1] (fn [obj arg0] (.setColumnReorderingAllowed obj arg0))
    [:setColumnWidth 2] (fn [obj arg0 arg1] (.setColumnWidth obj arg0 arg1))
    [:setColumns 1] (fn [obj arg0] (.setColumns obj arg0))
    [:setComponentAlignment 2] (fn [obj arg0 arg1] (.setComponentAlignment obj arg0 arg1))
    [:setComponentError 1] (fn [obj arg0] (.setComponentError obj arg0))
    [:setContainerDataSource 2] (fn [obj arg0 arg1] (.setContainerDataSource obj arg0 arg1))
    [:setContainerDataSource 6] (fn [obj arg0 arg1 arg2 arg3 arg4 arg5] (.setContainerDataSource obj arg0 arg1 arg2 arg3 arg4 arg5))
    [:setContainerDataSource 1] (fn [obj arg0] (.setContainerDataSource obj arg0))
    [:setContent 1] (fn [obj arg0] (.setContent obj arg0))
    [:setContentMode 1] (fn [obj arg0] (.setContentMode obj arg0))
    [:setConversionError 1] (fn [obj arg0] (.setConversionError obj arg0))
    [:setConvertedValue 1] (fn [obj arg0] (.setConvertedValue obj arg0))
    [:setConverter 1] (fn [obj arg0] (.setConverter obj arg0))
    [:setConverter 2] (fn [obj arg0 arg1] (.setConverter obj arg0 arg1))
    [:setCurrentBufferedSourceException 1] (fn [obj arg0] (.setCurrentBufferedSourceException obj arg0))
    [:setCurrentPageFirstItemId 1] (fn [obj arg0] (.setCurrentPageFirstItemId obj arg0))
    [:setCurrentPageFirstItemIndex 1] (fn [obj arg0] (.setCurrentPageFirstItemIndex obj arg0))
    [:setCursorPosition 1] (fn [obj arg0] (.setCursorPosition obj arg0))
    [:setCursorX 1] (fn [obj arg0] (.setCursorX obj arg0))
    [:setCursorY 1] (fn [obj arg0] (.setCursorY obj arg0))
    [:setData 1] (fn [obj arg0] (.setData obj arg0))
    [:setDateFormat 1] (fn [obj arg0] (.setDateFormat obj arg0))
    [:setDateOutOfRangeMessage 1] (fn [obj arg0] (.setDateOutOfRangeMessage obj arg0))
    [:setDebugId 1] (fn [obj arg0] (.setDebugId obj arg0))
    [:setDefaultComponentAlignment 1] (fn [obj arg0] (.setDefaultComponentAlignment obj arg0))
    [:setDescription 1] (fn [obj arg0] (.setDescription obj arg0))
    [:setDisableOnClick 1] (fn [obj arg0] (.setDisableOnClick obj arg0))
    [:setDragMode 1] (fn [obj arg0] (.setDragMode obj arg0))
    [:setDropHandler 1] (fn [obj arg0] (.setDropHandler obj arg0))
    [:setEditable 1] (fn [obj arg0] (.setEditable obj arg0))
    [:setEnabled 1] (fn [obj arg0] (.setEnabled obj arg0))
    [:setEndDate 1] (fn [obj arg0] (.setEndDate obj arg0))
    [:setErrorHandler 1] (fn [obj arg0] (.setErrorHandler obj arg0))
    [:setEventCaptionAsHtml 1] (fn [obj arg0] (.setEventCaptionAsHtml obj arg0))
    [:setEventProvider 1] (fn [obj arg0] (.setEventProvider obj arg0))
    [:setExpandRatio 2] (fn [obj arg0 arg1] (.setExpandRatio obj arg0 arg1))
    [:setFilteringMode 1] (fn [obj arg0] (.setFilteringMode obj arg0))
    [:setFirstComponent 1] (fn [obj arg0] (.setFirstComponent obj arg0))
    [:setFirstDayOfWeek 1] (fn [obj arg0] (.setFirstDayOfWeek obj arg0))
    [:setFirstVisibleDayOfWeek 1] (fn [obj arg0] (.setFirstVisibleDayOfWeek obj arg0))
    [:setFirstVisibleHourOfDay 1] (fn [obj arg0] (.setFirstVisibleHourOfDay obj arg0))
    [:setFooterVisible 1] (fn [obj arg0] (.setFooterVisible obj arg0))
    [:setHandler 1] (fn [obj arg0] (.setHandler obj arg0))
    [:setHeight 2] (fn [obj arg0 arg1] (.setHeight obj arg0 arg1))
    [:setHeight 1] (fn [obj arg0] (.setHeight obj arg0))
    [:setHeightUndefined 0] (fn [obj ] (.setHeightUndefined obj ))
    [:setHideEmptyRowsAndColumns 1] (fn [obj arg0] (.setHideEmptyRowsAndColumns obj arg0))
    [:setHierarchyColumn 1] (fn [obj arg0] (.setHierarchyColumn obj arg0))
    [:setHtmlContentAllowed 1] (fn [obj arg0] (.setHtmlContentAllowed obj arg0))
    [:setIcon 1] (fn [obj arg0] (.setIcon obj arg0))
    [:setIcon 2] (fn [obj arg0 arg1] (.setIcon obj arg0 arg1))
    [:setIconAlternateText 1] (fn [obj arg0] (.setIconAlternateText obj arg0))
    [:setId 1] (fn [obj arg0] (.setId obj arg0))
    [:setImmediate 1] (fn [obj arg0] (.setImmediate obj arg0))
    [:setInputPrompt 1] (fn [obj arg0] (.setInputPrompt obj arg0))
    [:setInvalidAllowed 1] (fn [obj arg0] (.setInvalidAllowed obj arg0))
    [:setInvalidCommitted 1] (fn [obj arg0] (.setInvalidCommitted obj arg0))
    [:setItemCaption 2] (fn [obj arg0 arg1] (.setItemCaption obj arg0 arg1))
    [:setItemCaptionMode 1] (fn [obj arg0] (.setItemCaptionMode obj arg0))
    [:setItemCaptionPropertyId 1] (fn [obj arg0] (.setItemCaptionPropertyId obj arg0))
    [:setItemDescriptionGenerator 1] (fn [obj arg0] (.setItemDescriptionGenerator obj arg0))
    [:setItemEnabled 2] (fn [obj arg0 arg1] (.setItemEnabled obj arg0 arg1))
    [:setItemIcon 2] (fn [obj arg0 arg1] (.setItemIcon obj arg0 arg1))
    [:setItemIcon 3] (fn [obj arg0 arg1 arg2] (.setItemIcon obj arg0 arg1 arg2))
    [:setItemIconAlternateText 2] (fn [obj arg0 arg1] (.setItemIconAlternateText obj arg0 arg1))
    [:setItemIconPropertyId 1] (fn [obj arg0] (.setItemIconPropertyId obj arg0))
    [:setItemStyleGenerator 1] (fn [obj arg0] (.setItemStyleGenerator obj arg0))
    [:setLastVisibleDayOfWeek 1] (fn [obj arg0] (.setLastVisibleDayOfWeek obj arg0))
    [:setLastVisibleHourOfDay 1] (fn [obj arg0] (.setLastVisibleHourOfDay obj arg0))
    [:setLeftColumnCaption 1] (fn [obj arg0] (.setLeftColumnCaption obj arg0))
    [:setLenient 1] (fn [obj arg0] (.setLenient obj arg0))
    [:setLocale 1] (fn [obj arg0] (.setLocale obj arg0))
    [:setLocked 1] (fn [obj arg0] (.setLocked obj arg0))
    [:setMargin 1] (fn [obj arg0] (.setMargin obj arg0))
    [:setMax 1] (fn [obj arg0] (.setMax obj arg0))
    [:setMaxLength 1] (fn [obj arg0] (.setMaxLength obj arg0))
    [:setMaxSplitPosition 2] (fn [obj arg0 arg1] (.setMaxSplitPosition obj arg0 arg1))
    [:setMimeType 1] (fn [obj arg0] (.setMimeType obj arg0))
    [:setMin 1] (fn [obj arg0] (.setMin obj arg0))
    [:setMinSplitPosition 2] (fn [obj arg0 arg1] (.setMinSplitPosition obj arg0 arg1))
    [:setMoreMenuItem 1] (fn [obj arg0] (.setMoreMenuItem obj arg0))
    [:setMultiSelect 1] (fn [obj arg0] (.setMultiSelect obj arg0))
    [:setMultiSelectMode 1] (fn [obj arg0] (.setMultiSelectMode obj arg0))
    [:setMultiselectMode 1] (fn [obj arg0] (.setMultiselectMode obj arg0))
    [:setNewItemHandler 1] (fn [obj arg0] (.setNewItemHandler obj arg0))
    [:setNewItemsAllowed 1] (fn [obj arg0] (.setNewItemsAllowed obj arg0))
    [:setNullRepresentation 1] (fn [obj arg0] (.setNullRepresentation obj arg0))
    [:setNullSelectionAllowed 1] (fn [obj arg0] (.setNullSelectionAllowed obj arg0))
    [:setNullSelectionItemId 1] (fn [obj arg0] (.setNullSelectionItemId obj arg0))
    [:setNullSettingAllowed 1] (fn [obj arg0] (.setNullSettingAllowed obj arg0))
    [:setOrientation 1] (fn [obj arg0] (.setOrientation obj arg0))
    [:setPageLength 1] (fn [obj arg0] (.setPageLength obj arg0))
    [:setParameter 2] (fn [obj arg0 arg1] (.setParameter obj arg0 arg1))
    [:setParent 1] (fn [obj arg0] (.setParent obj arg0))
    [:setParent 2] (fn [obj arg0 arg1] (.setParent obj arg0 arg1))
    [:setParseErrorMessage 1] (fn [obj arg0] (.setParseErrorMessage obj arg0))
    [:setPrimaryStyleName 1] (fn [obj arg0] (.setPrimaryStyleName obj arg0))
    [:setPropertyDataSource 1] (fn [obj arg0] (.setPropertyDataSource obj arg0))
    [:setRangeEnd 1] (fn [obj arg0] (.setRangeEnd obj arg0))
    [:setRangeStart 1] (fn [obj arg0] (.setRangeStart obj arg0))
    [:setReadOnly 1] (fn [obj arg0] (.setReadOnly obj arg0))
    [:setReceiver 1] (fn [obj arg0] (.setReceiver obj arg0))
    [:setRequired 1] (fn [obj arg0] (.setRequired obj arg0))
    [:setRequiredError 1] (fn [obj arg0] (.setRequiredError obj arg0))
    [:setResolution 1] (fn [obj arg0] (.setResolution obj arg0))
    [:setResource 1] (fn [obj arg0] (.setResource obj arg0))
    [:setResponsive 1] (fn [obj arg0] (.setResponsive obj arg0))
    [:setRightColumnCaption 1] (fn [obj arg0] (.setRightColumnCaption obj arg0))
    [:setRowExpandRatio 2] (fn [obj arg0 arg1] (.setRowExpandRatio obj arg0 arg1))
    [:setRowGenerator 1] (fn [obj arg0] (.setRowGenerator obj arg0))
    [:setRowHeaderMode 1] (fn [obj arg0] (.setRowHeaderMode obj arg0))
    [:setRows 1] (fn [obj arg0] (.setRows obj arg0))
    [:setScrollLeft 1] (fn [obj arg0] (.setScrollLeft obj arg0))
    [:setScrollToSelectedItem 1] (fn [obj arg0] (.setScrollToSelectedItem obj arg0))
    [:setScrollTop 1] (fn [obj arg0] (.setScrollTop obj arg0))
    [:setSecondComponent 1] (fn [obj arg0] (.setSecondComponent obj arg0))
    [:setSelectable 1] (fn [obj arg0] (.setSelectable obj arg0))
    [:setSelectedTab 1] (fn [obj arg0] (.setSelectedTab obj arg0))
    [:setSelectionRange 2] (fn [obj arg0 arg1] (.setSelectionRange obj arg0 arg1))
    [:setShowISOWeekNumbers 1] (fn [obj arg0] (.setShowISOWeekNumbers obj arg0))
    [:setSizeFull 0] (fn [obj ] (.setSizeFull obj ))
    [:setSizeUndefined 0] (fn [obj ] (.setSizeUndefined obj ))
    [:setSortAscending 1] (fn [obj arg0] (.setSortAscending obj arg0))
    [:setSortContainerPropertyId 1] (fn [obj arg0] (.setSortContainerPropertyId obj arg0))
    [:setSortDisabled 1] (fn [obj arg0] (.setSortDisabled obj arg0))
    [:setSortEnabled 1] (fn [obj arg0] (.setSortEnabled obj arg0))
    [:setSource 1] (fn [obj arg0] (.setSource obj arg0))
    [:setSpacing 1] (fn [obj arg0] (.setSpacing obj arg0))
    [:setSplitPosition 3] (fn [obj arg0 arg1 arg2] (.setSplitPosition obj arg0 arg1 arg2))
    [:setSplitPosition 2] (fn [obj arg0 arg1] (.setSplitPosition obj arg0 arg1))
    [:setSplitPosition 1] (fn [obj arg0] (.setSplitPosition obj arg0))
    [:setStandby 1] (fn [obj arg0] (.setStandby obj arg0))
    [:setStartDate 1] (fn [obj arg0] (.setStartDate obj arg0))
    [:setStyleName 1] (fn [obj arg0] (.setStyleName obj arg0))
    [:setStyleName 2] (fn [obj arg0 arg1] (.setStyleName obj arg0 arg1))
    [:setTabCaptionsAsHtml 1] (fn [obj arg0] (.setTabCaptionsAsHtml obj arg0))
    [:setTabIndex 1] (fn [obj arg0] (.setTabIndex obj arg0))
    [:setTabPosition 2] (fn [obj arg0 arg1] (.setTabPosition obj arg0 arg1))
    [:setTableFieldFactory 1] (fn [obj arg0] (.setTableFieldFactory obj arg0))
    [:setTabsVisible 1] (fn [obj arg0] (.setTabsVisible obj arg0))
    [:setTargetBorder 1] (fn [obj arg0] (.setTargetBorder obj arg0))
    [:setTargetHeight 1] (fn [obj arg0] (.setTargetHeight obj arg0))
    [:setTargetName 1] (fn [obj arg0] (.setTargetName obj arg0))
    [:setTargetWidth 1] (fn [obj arg0] (.setTargetWidth obj arg0))
    [:setTextChangeEventMode 1] (fn [obj arg0] (.setTextChangeEventMode obj arg0))
    [:setTextChangeTimeout 1] (fn [obj arg0] (.setTextChangeTimeout obj arg0))
    [:setTextFieldEnabled 1] (fn [obj arg0] (.setTextFieldEnabled obj arg0))
    [:setTextInputAllowed 1] (fn [obj arg0] (.setTextInputAllowed obj arg0))
    [:setTimeFormat 1] (fn [obj arg0] (.setTimeFormat obj arg0))
    [:setTimeZone 1] (fn [obj arg0] (.setTimeZone obj arg0))
    [:setType 1] (fn [obj arg0] (.setType obj arg0))
    [:setValidationVisible 1] (fn [obj arg0] (.setValidationVisible obj arg0))
    [:setValue 1] (fn [obj arg0] (.setValue obj arg0))
    [:setVisible 1] (fn [obj arg0] (.setVisible obj arg0))
    [:setVisibleColumns 1] (fn [obj arg0] (.setVisibleColumns obj arg0))
    [:setWeeklyCaptionFormat 1] (fn [obj arg0] (.setWeeklyCaptionFormat obj arg0))
    [:setWidth 2] (fn [obj arg0 arg1] (.setWidth obj arg0 arg1))
    [:setWidth 1] (fn [obj arg0] (.setWidth obj arg0))
    [:setWidthUndefined 0] (fn [obj ] (.setWidthUndefined obj ))
    [:setWordwrap 1] (fn [obj arg0] (.setWordwrap obj arg0))
})